import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'


import { RiTodoLine } from "react-icons/ri";
import { useEffect, useState } from 'react'
import Tablero from '../components/Tablero';
const inter = Inter({ subsets: ['latin'] })



export default function Home() {

  
 return (
    <>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className='w-auto border-b-2 border-black'>
        <div className='bg-green-600 flex justify-center items-center p-2'>
          <RiTodoLine width={40} height={40}></RiTodoLine>
        </div>
        <div>
          <h2 className=' text-slate-900 font-bold font-serif p-2'>Desarrollos</h2>
        </div>

        
      </header>
    <Tablero></Tablero>

    
    </>
  )
}
